name: conn_ve
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: 1.8.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

dependency_overrides:
  sign_in_with_apple:
    path: sign_in_with_apple_dummy

